accessing
exception
	"Relation named: #exception type: #PythonException opposite: #exceptionAssociation"

	<generated>
	^ exception