accessing
exception
	"Relation named: #exception type: #FastPythonException opposite: #raise"

	<generated>
	^ exception