accessing
exceptionHandler: anObject

	<generated>
	exceptionHandler := anObject